### ISSUE TITLE
Feature request - maximum number of attempts for accessing the download

### ISSUE THREAD

**Issue by mdkwant** [eodms-sgdot/py-eodms-rapi#10]
Request to add feature to have a maximum number of attempts the download query will try to attempt to download. Where a timetout error is given when the maximum number of attempts is reached. 
Use case: We use this script operationally and sometimes server space is needed after say x ammount of time. We need to have the option to stop the script after x ammount of time is passed so other activities can be started.

in line 1389

`    def download(self, items, dest, wait=60.0, attempts=5):`

and in line 1447 - 1455

`        attempt = 1
        complete_items = []
        while len(unique_items) > len(complete_items) and attempt <= attempts:
            time.sleep(wait)
            attempt += 1
            
            # start, end = self._get_dateRange(unique_items)
            # orders = self.get_orders(dtstart=start, dtend=end)
            orders = self.get_orders()`

![image](https://user-images.githubusercontent.com/31434182/164194516-3c4d371b-2962-49d0-a674-38e920eaa84c.png)

**Comment by mdkwant** [comment]
And including a log message when maximum number is reached: 

Line 1457:

            if attempt > attempts:
                msg = "Maximum number of attempts reached"
                self._log_msg(msg)
                return []

**Comment by keballantyne** [comment]
Maximum attempts has been added when downloading images for v1.4.0
