### ISSUE TITLE
Network interruption causes downloading to fail and not recover

### ISSUE THREAD

**Issue by richardburcher** [eodms-sgdot/py-eodms-rapi#20]
Network interruption when downloading causes Python API to fail. The order is still processed and sent to my email to download via other means.

Queries/Thoughts:
1. Perhaps I should be only passing one productID at a time instead of filtered search and check for failure? Through it would be great if the downloader would recover from network interruptions i.e. I disconnect from vpn.
2. If the downloading can not recover, then the order should be cancelled. I mistakenly restarted the script and had two identical orders waiting in my email. I do not want to consume more resources than necessary from the system.

Thanks so much for this API!

![2022-02-18-eodms-python-api-does-not-handle-network-issues](https://user-images.githubusercontent.com/60985476/155349259-ee6235a0-ac76-4c7e-9b5f-38231cc981bd.png)

**Comment by keballantyne** [comment]
This issue originated in eodms-cli, however it has also been transferred here since the fix will be made in the py-eodms-rapi Python package.

**Comment by keballantyne** [comment]
Issue has been fixed with v1.5.2 https://github.com/eodms-sgdot/py-eodms-rapi/commit/8398a492c93d1df6f60964965b37776d9241b659
