### ISSUE TITLE
Error runing documentation example

### ISSUE THREAD

**Issue by yreynaud** [eodms-sgdot/py-eodms-rapi#30]
I wanted to try using the API by first searching products (dates and coordinates), and then making an order of these product. So, I first tried using the concerned example in the documentation (here : https://py-eodms-rapi.readthedocs.io/en/latest/). But it doesn't run correctly. Here is the returned error : 
![image](https://github.com/eodms-sgdot/py-eodms-rapi/assets/94846335/1f2fa6d5-0e03-4ecb-89fc-0a7f87340452)
Then I tried to replace 'filters' by None and it runs correctly.

**Comment by keballantyne** [comment]
Fixed in release v.1.5.6 (https://github.com/eodms-sgdot/py-eodms-rapi/commit/175a11239af061c7b83e00a20a497eb39ebe6955)
